name = "AI Slower"
description = "Modifies AIs on the server to make them update slow."
author = "Wurt.fun"
version = "rdev-0241714"
forumthread = ""
api_version = 10
dst_compatible = true
client_only_mod = false
all_clients_require_mod = true